on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print SSH private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"
  
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
      - name: Deploy code
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@51.38.125.55 "cd /home/ubuntu/musicBot/MusicBot && git pull origin main"

