on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: connect and pull
      run: ssh ubuntu@51.38.125.55 "cd  && /home/ubuntu/musicBot/MusicBot && git checkout main && git pull && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
